ALTER TABLE PRODUCT
	DROP
		CONSTRAINT FK_CATEGORY_TO_PRODUCT
		CASCADE;

ALTER TABLE PRODUCT
	DROP
		PRIMARY KEY
		CASCADE
		KEEP INDEX;

DROP INDEX PK_PRODUCT;

/* 상품 */
DROP TABLE PRODUCT 
	CASCADE CONSTRAINTS;

/* 상품 */
CREATE TABLE PRODUCT (
	PNUM NUMBER(8) NOT NULL, /* 상품번호 */
	PNAME VARCHAR2(100) NOT NULL, /* 상품명 */
	PCOMPANY VARCHAR2(50) NOT NULL, /* 제조사 */
	PIMG1 VARCHAR2(200), /* 상품이미지1 */
	PIMG2 VARCHAR2(200), /* 상품이미지2 */
	PIMG3 VARCHAR2(200), /* 상품이미지3 */
	PQTY NUMBER(8), /* 수량 */
	PRICE NUMBER(8) NOT NULL, /* 상품정가 */
	SALEPRICE NUMBER(8) NOT NULL, /* 상품판매가 */
	PSPEC VARCHAR2(20), /* 상품스팩 */
	PCONTENTS VARCHAR2(1000), /* 상품설명 */
	POINT NUMBER(8), /* 포인트 */
	PINDATE DATE, /* 상품입고일 */
	CG_NUM_FK NUMBER(8) /* 카테고리번호 */
);

COMMENT ON TABLE PRODUCT IS '상품';

COMMENT ON COLUMN PRODUCT.PNUM IS '상품번호';

COMMENT ON COLUMN PRODUCT.PNAME IS '상품명';

COMMENT ON COLUMN PRODUCT.PCOMPANY IS '제조사';

COMMENT ON COLUMN PRODUCT.PIMG1 IS '상품이미지1';

COMMENT ON COLUMN PRODUCT.PIMG2 IS '상품이미지2';

COMMENT ON COLUMN PRODUCT.PIMG3 IS '상품이미지3';

COMMENT ON COLUMN PRODUCT.PQTY IS '수량';

COMMENT ON COLUMN PRODUCT.PRICE IS '상품정가';

COMMENT ON COLUMN PRODUCT.SALEPRICE IS '상품판매가';

COMMENT ON COLUMN PRODUCT.PSPEC IS '상품스팩';

COMMENT ON COLUMN PRODUCT.PCONTENTS IS '상품설명';

COMMENT ON COLUMN PRODUCT.POINT IS '포인트';

COMMENT ON COLUMN PRODUCT.PINDATE IS '상품입고일';

COMMENT ON COLUMN PRODUCT.CG_NUM_FK IS '카테고리번호';

CREATE UNIQUE INDEX PK_PRODUCT
	ON PRODUCT (
		PNUM ASC
	);

ALTER TABLE PRODUCT
	ADD
		CONSTRAINT PK_PRODUCT
		PRIMARY KEY (
			PNUM
		);

ALTER TABLE PRODUCT
	ADD
		CONSTRAINT FK_CATEGORY_TO_PRODUCT
		FOREIGN KEY (
			CG_NUM_FK
		)
		REFERENCES CATEGORY (
			CG_NUM
		);
        
        
DROP SEQUENCE PRODUCT_SEQ;

CREATE SEQUENCE PRODUCT_SEQ NOCACHE;


sele