CREATE OR REPLACE PROCEDURE UPDATE_SAL
(VEMPNO IN EMP.EMPNO%TYPE)
IS
BEGIN
    UPDATE EMP
    SET SAL = SAL * 1.5
    WHERE EMPNO LIKE VEMPNO;
    COMMIT;
END;
/

EXEC UPDATE_SAL(7369);

SELECT * FROM EMP;

SELECT MAX(DEPTNO) FROM DEPT;

DROP SEQUENCE DEPT_SEQ;

CREATE SEQUENCE DEPT_SEQ
START WITH 60
INCREMENT BY 10
NOCACHE;


SELECT * FROM DEPT;

ALTER TABLE DEPT
MODIFY DEPTNO NUMBER(4);

DESC DEPT;

CREATE SEQUENCE EMP_SEQ
START WITH 8000
INCREMENT BY 1
NOCACHE;

select * from emp order by empno desc;

CREATE OR REPLACE PROCEDURE EMP_MODIFY
(VDNAME IN VARCHAR2,
 VEMPNO IN EMP.EMPNO%TYPE,
 VENAME IN EMP.ENAME%TYPE,
 VJOB IN EMP.JOB%TYPE)
IS
BEGIN
    UPDATE EMP 
    SET DEPTNO = (SELECT DEPTNO
                         FROM DEPT
                         WHERE DEPTNO LIKE VDNAME);
    UPDATE EMP
    SET ENAME = VENAME
    WHERE EMPNO LIKE VEMPNO;
    
    UPDATE EMP
    SET JOB = VJOB
    WHERE EMPNO LIKE VEMPNO;
END;
/

drop procedure emp_modify;

SELECT * FROM EMP;

UPDATE EMP 
SET ENAME = 'FFF', JOB ='DDD',
      DEPTNO = (SELECT DEPTNO
                      FROM DEPT
                      WHERE DNAME LIKE 'SALES')
WHERE EMPNO LIKE 8000;
ROLLBACK;
COMMIT;

