CREATE TABLE MEMBERS(
    MID NUMBER, -- PK
    LOGIN VARCHAR2(20), -- UNIQUE
    PWD VARCHAR2(20) CONSTRAINT NN_MB_PWD NOT NULL,
    NAME CHAR(4) CONSTRAINT NN_MB_NAME NOT NULL,
    GENDER NUMBER CONSTRAINT CHK_MB_GENDER CHECK(GENDER IN (1, 2)) NOT NULL,
    BIRTH DATE NOT NULL,
    EMAIL VARCHAR2(100),
    PHONE VARCHAR2(15) CHECK (REGEXP_LIKE(PHONE, '^01[01]-\d{3,4}-\d{4}$')),
    PID NUMBER, --FK
    CONSTRAINT PK_MB_MID PRIMARY KEY (MID),
    CONSTRAINT UN_MB_LOGIN UNIQUE (LOGIN),
    CONSTRAINT FK_MB_PID FOREIGN KEY(PID) REFERENCES PRODUCT(PID)
);

CREATE TABLE PRODUCT(
    PID NUMBER,
    PNAME VARCHAR2(50),
    CATEGORY VARCHAR2(30) NOT NULL,
    PRICE NUMBER(10) NOT NULL,
    REGDAY DATE DEFAULT SYSDATE NOT NULL,
    IMAGED VARCHAR2(100) NOT NULL,
    HT_KIND VARCHAR2(10) CONSTRAINT CHK_PT_HT CHECK(HT_KIND IN ('ICE', 'HOT')),
    CONSTRAINT PK_PT_PID PRIMARY KEY (PID),
    CONSTRAINT UN_PT_PNAME UNIQUE (PNAME)
);

CREATE TABLE ADMIN(
    AID NUMBER,
    LOGIN VARCHAR2(20),
    PWD VARCHAR2(20) NOT NULL,
    NAME VARCHAR2(5),
    MID NUMBER,
    PID NUMBER,
    CONSTRAINT PK_AN_AID PRIMARY KEY(AID),
    CONSTRAINT UN_AN_LOGIN UNIQUE(LOGIN),
    CONSTRAINT FK_AN_MID FOREIGN KEY (MID) REFERENCES MEMBERS(MID),
    CONSTRAINT FK_AN_PID FOREIGN KEY (PID) REFERENCES PRODUCT(PID)
);


-----------------------------------------------------------------------------------------
--FOR LOOR 
CREATE OR REPLACE PROCEDURE DEPT_EMPINFO
(DNO IN DEPT.DEPTNO%TYPE)
IS
VEMP EMP%ROWTYPE;
BEGIN
    FOR J IN (SELECT EMPNO, ENAME, DEPTNO
                 FROM EMP
                 WHERE DEPTNO LIKE DNO) LOOP  
    DBMS_OUTPUT.PUT_LINE('사번' ||J.EMPNO);
    DBMS_OUTPUT.PUT_LINE('이름' ||J.ENAME);
    DBMS_OUTPUT.PUT_LINE('부서번호' ||J.DEPTNO);
    END LOOP;
    EXCEPTION 
    WHEN TOO_MANY_ROWS THEN 
        DBMS_OUTPUT.PUT_LINE('TOO MANY ROWS : 데이터가 너무 많아요');
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('데이터가 없어요');
    WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE('기타 에러 발생');
END;
/
-------------------------------------------------------------------------------
SET SERVEROUTPUT ON

EXEC DEPT_EMPINFO(0);

