CREATE TABLE MEMBERS(
    MSEQ NUMBER NOT  NULL, --SEQUENCE
    MID VARCHAR2(20), --PK
    PWD VARCHAR2(20) CONSTRAINT NN_MB_PWD NOT NULL,
    MNAME CHAR(4) CONSTRAINT NN_MB_NAME NOT NULL,
    GENDER NUMBER CONSTRAINT CHK_MB_GENDER CHECK(GENDER IN (1, 2)) NOT NULL,
    BIRTH DATE NOT NULL,
    EMAIL VARCHAR2(100),
    PHONE VARCHAR2(15) CHECK (REGEXP_LIKE(PHONE, '^01[01]-\d{3,4}-\d{4}$')),
    CONSTRAINT PK_MB_LOGIN PRIMARY KEY  (MID)
);
COMMENT ON COLUMN MEMBERS.MSEQ IS '회원번호';
COMMENT ON COLUMN MEMBERS.MID IS '아이디';
COMMENT ON COLUMN MEMBERS.PWD IS '비밀번호';
COMMENT ON COLUMN MEMBERS.MNAME IS '이름';
COMMENT ON COLUMN MEMBERS.GENDER IS '성별';
COMMENT ON COLUMN MEMBERS.BIRTH IS '생년월일';
COMMENT ON COLUMN MEMBERS.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBERS.PHONE IS '휴대폰 번호';


CREATE TABLE PRODUCT(
    PSEQ NUMBER NOT NULL,
    PT_NAME VARCHAR2(50),
    CATEGORY VARCHAR2(30) NOT NULL,
    PRICE NUMBER(10) NOT NULL,
    REGDAY DATE DEFAULT SYSDATE NOT NULL,
    IMAGED VARCHAR2(100) NOT NULL,
    HT_KIND VARCHAR2(10) CONSTRAINT CHK_PT_HT CHECK(HT_KIND IN ('ICE', 'HOT')),
    CONSTRAINT UN_PT_NAME UNIQUE (PT_NAME)
);
COMMENT ON COLUMN PRODUCT.PSEQ IS '상품번호';
COMMENT ON COLUMN PRODUCT.PT_NAME IS '상품이름';
COMMENT ON COLUMN PRODUCT.CATEGORY IS '상품 카테고리';
COMMENT ON COLUMN PRODUCT.PRICE IS '가격';
COMMENT ON COLUMN PRODUCT.REGDAY IS '등록날짜';
COMMENT ON COLUMN PRODUCT.IMAGED IS '이미지경로';
COMMENT ON COLUMN PRODUCT.HT_KIND IS 'HOT/ICE';

CREATE TABLE ADMIN(
    ASEQ NUMBER NOT NULL,
    AID VARCHAR2(20),
    PWD VARCHAR2(20) NOT NULL,
    ANAME VARCHAR2(10),
    MID NUMBER, --MEMBERS PK
    PT_NAME VARCHAR2(50), --PRODUCT PK
    CONSTRAINT PK_AN_AID PRIMARY KEY(AID),
    CONSTRAINT FK_AN_MID FOREIGN KEY (MID) REFERENCES MEMBERS(MID) ON DELETE CASCADE,
    CONSTRAINT FK_AN_PID FOREIGN KEY (PT_NAME) REFERENCES PRODUCT(PT_NAME) ON DELETE CASCADE
);
COMMENT ON COLUMN ADMIN.ASEQ IS '관리자 번호';
COMMENT ON COLUMN ADMIN.AID IS '관리자 아이디';
COMMENT ON COLUMN ADMIN.PWD IS '비밀번호';
COMMENT ON COLUMN ADMIN.ANAME IS '이름';

CREATE TABLE ORDER(
    OSEQ NUMBER, -- 시퀀스
    ORDER_NUMBER VARCHAR2(20) NOT NULL,
    QUANTITY NUMBER(3) NOT NULL,
    TOTAL_PRICE NUMBER NOT NULL,
    ORDER_TIME DATE DEFAULT SYSDATE,
    ORDER_STATUS NUMBER NOT NULL,
    PT_NAME VARCHAR2(50),
    MID VARCHAR2(30),
    CONSTRAINT PK_OR_OID PRIMARY KEY (OID),
    CONSTRAINT CHK_OR_STATUS CHECK(ORDER_STATUS  IN (1, 2, 3)),
    CONSTRAINT FK_OR_NAME FOREIGN KEY (NAME) REFERENCES PRODUCT(PT_NAME) ON DELETE CASCADE,
    CONSTRAINT FK_OR_ID FOREIGN KEY (MID) REFERENCES MEMBERS (MID) ON DELETE CASCADE
);
COMMENT ON COLUMN ORDER.OSEQ IS '주문관리번호';
COMMENT ON COLUMN ORDER.ORDER_NUMBER IS '주문번호';
COMMENT ON COLUMN ORDER.QUANTITY IS '수량';
COMMENT ON COLUMN ORDER.TOTAL_PRICE IS '총가격';
COMMENT ON COLUMN ORDER.ORDER_TIME IS '주문시간';
COMMENT ON COLUMN ORDER.ORDER_STATUS IS '주문상태';

CREATE  SEQUENCE MEMBER_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE ADMIN_SEQ
START WITH 50
INCREMENT BY 5
NOCACHE;

CREATE SEQUENCE PRODUCT_SEQ
START WITH 100
INCREMENT BY 10
NOCACHE;

CREATE SEQUENCE ORDER_SEQ
START WITH 150
INCREMENT BY 20
NOCACHE;
